// Code generated by MockGen. DO NOT EDIT.
// Source: signerapp/expected_interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	btcec "github.com/btcsuite/btcd/btcec/v2"
	gomock "github.com/golang/mock/gomock"
)

// MockPrivKeyRetriever is a mock of PrivKeyRetriever interface.
type MockPrivKeyRetriever struct {
	ctrl     *gomock.Controller
	recorder *MockPrivKeyRetrieverMockRecorder
}

// MockPrivKeyRetrieverMockRecorder is the mock recorder for MockPrivKeyRetriever.
type MockPrivKeyRetrieverMockRecorder struct {
	mock *MockPrivKeyRetriever
}

// NewMockPrivKeyRetriever creates a new mock instance.
func NewMockPrivKeyRetriever(ctrl *gomock.Controller) *MockPrivKeyRetriever {
	mock := &MockPrivKeyRetriever{ctrl: ctrl}
	mock.recorder = &MockPrivKeyRetrieverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivKeyRetriever) EXPECT() *MockPrivKeyRetrieverMockRecorder {
	return m.recorder
}

// PrivKey mocks base method.
func (m *MockPrivKeyRetriever) PrivKey(ctx context.Context) (*btcec.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivKey", ctx)
	ret0, _ := ret[0].(*btcec.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrivKey indicates an expected call of PrivKey.
func (mr *MockPrivKeyRetrieverMockRecorder) PrivKey(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivKey", reflect.TypeOf((*MockPrivKeyRetriever)(nil).PrivKey), ctx)
}
