name: ci

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
      
jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@5151754256060bf160c411d0784f831f29882106 # v0.13.4
    with:
      go-version: '1.25'
      go-lint-version: 'v2.4.0'
      run-unit-tests: true
      run-integration-tests: true
      run-lint: true
      run-build: true
      run-gosec: true
      gosec-args: "-exclude-generated -exclude-dir=itest -exclude-dir=testutil -exclude-dir=covenant-signer ./..."

  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@5151754256060bf160c411d0784f831f29882106 # v0.13.4
    secrets: inherit
    with:
      publish: false
      dockerfile: ./Dockerfile
      repoName: covenant-emulator
      docker_scan: true

  go_sec_covenant_signer:
    runs-on: ubuntu-24.04
    env:
      GO111MODULE: on
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.25.x'
          check-latest: true
          cache: false
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Gosec (covenant-signer)
        working-directory: ./covenant-signer
        run: gosec ./...

  docker_pipeline_covenant_signer:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@5151754256060bf160c411d0784f831f29882106 # v0.13.4
    secrets: inherit
    with:
      publish: false
      dockerfile: ./covenant-signer/Dockerfile
      dockerContext: ./
      repoName: covenant-signer
      docker_scan: true
