name: ci

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@v0.11.2
    with:
      go-version: '1.23'
      go-lint-version: 'v1.60.2'
      run-unit-tests: true
      run-integration-tests: false
      run-lint: true
      run-build: true
      run-gosec: true
      gosec-args: "-exclude-generated -exclude-dir=itest -exclude-dir=testutil -exclude-dir=covenant-signer ./..."

  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.11.2
    secrets: inherit
    with:
      publish: false
      dockerfile: ./Dockerfile
      repoName: covenant-emulator
      docker_scan: true

  go_sec_covenant_signer:
    runs-on: ubuntu-24.04
    env:
      GO111MODULE: on
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.23.x'
          check-latest: true
          cache: false
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Gosec (covenant-signer)
        working-directory: ./covenant-signer
        run: gosec ./...

  docker_pipeline_covenant_signer:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.11.2
    secrets: inherit
    with:
      publish: false
      dockerfile: ./covenant-signer/Dockerfile
      dockerContext: ./
      repoName: covenant-signer
      docker_scan: true

###############################################################################
###                                   E2E                                   ###
###############################################################################

  e2e-cov-signer:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Cache Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.23.1
        - name: Run e2e covenant signer
          run: |
            cd covenant-signer; make test-e2e

  e2e-cov-emulator-life:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Cache Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.23.1
        - name: Run e2e covenant emulator life cycle
          run: |
            make test-e2e-cov-emu-life

  e2e-cov-pending-dels:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Cache Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.23.1
        - name: Run e2e covenant emulator pending dels
          run: |
            make test-e2e-cov-pending-del