name: goreleaser

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
<<<<<<< HEAD
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_releaser.yml@v0.7.0
=======
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_releaser.yml@0adff9d36a387ebfc921621f2e6b357230f8c08e # v0.18.0 and up
>>>>>>> 1da7d5c (chore: copy workflow from babylon (#184))
    secrets: inherit